// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DataTapiEquipmentGetDeviceListPostInput data tapi equipment get device list post input
// swagger:model data_tapi-equipment_get-device-list-post-input
type DataTapiEquipmentGetDeviceListPostInput interface{}
