// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DataTapiConnectivityGetConnectivityServiceDetailsPostInput data tapi connectivity get connectivity service details post input
// swagger:model data_tapi-connectivity_get-connectivity-service-details-post-input
type DataTapiConnectivityGetConnectivityServiceDetailsPostInput struct {

	// none (leaf)
	TapiConnectivityServiceIDOrName string `json:"tapi-connectivity:service-id-or-name,omitempty"`
}

// Validate validates this data tapi connectivity get connectivity service details post input
func (m *DataTapiConnectivityGetConnectivityServiceDetailsPostInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataTapiConnectivityGetConnectivityServiceDetailsPostInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataTapiConnectivityGetConnectivityServiceDetailsPostInput) UnmarshalBinary(b []byte) error {
	var res DataTapiConnectivityGetConnectivityServiceDetailsPostInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
