// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DataTapiTopologyGetLinkDetailsPostInput data tapi topology get link details post input
// swagger:model data_tapi-topology_get-link-details-post-input
type DataTapiTopologyGetLinkDetailsPostInput struct {

	// none (leaf)
	TapiTopologyLinkIDOrName string `json:"tapi-topology:link-id-or-name,omitempty"`

	// none (leaf)
	TapiTopologyTopologyIDOrName string `json:"tapi-topology:topology-id-or-name,omitempty"`
}

// Validate validates this data tapi topology get link details post input
func (m *DataTapiTopologyGetLinkDetailsPostInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataTapiTopologyGetLinkDetailsPostInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataTapiTopologyGetLinkDetailsPostInput) UnmarshalBinary(b []byte) error {
	var res DataTapiTopologyGetLinkDetailsPostInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
