// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DataTapiNetworkElementGetNetworkElementDetailsPostOutput data tapi network element get network element details post output
// swagger:model data_tapi-network-element_get-network-element-details-post-output
type DataTapiNetworkElementGetNetworkElementDetailsPostOutput struct {

	// tapi network element network element
	TapiNetworkElementNetworkElement *DataTapiNetworkElementGetNetworkElementDetailsPostOutputTapiNetworkElementNetworkElement `json:"tapi-network-element:network-element,omitempty"`
}

// Validate validates this data tapi network element get network element details post output
func (m *DataTapiNetworkElementGetNetworkElementDetailsPostOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTapiNetworkElementNetworkElement(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DataTapiNetworkElementGetNetworkElementDetailsPostOutput) validateTapiNetworkElementNetworkElement(formats strfmt.Registry) error {

	if swag.IsZero(m.TapiNetworkElementNetworkElement) { // not required
		return nil
	}

	if m.TapiNetworkElementNetworkElement != nil {
		if err := m.TapiNetworkElementNetworkElement.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tapi-network-element:network-element")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DataTapiNetworkElementGetNetworkElementDetailsPostOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataTapiNetworkElementGetNetworkElementDetailsPostOutput) UnmarshalBinary(b []byte) error {
	var res DataTapiNetworkElementGetNetworkElementDetailsPostOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DataTapiNetworkElementGetNetworkElementDetailsPostOutputTapiNetworkElementNetworkElement none (non-presence)
// swagger:model DataTapiNetworkElementGetNetworkElementDetailsPostOutputTapiNetworkElementNetworkElement
type DataTapiNetworkElementGetNetworkElementDetailsPostOutputTapiNetworkElementNetworkElement struct {

	// none (leaf)
	IP string `json:"ip,omitempty"`

	// Indication that the Network Element is Discoverable. (leaf)
	IsDiscoverable bool `json:"isDiscoverable,omitempty"`

	// none (leaf)
	Latitude string `json:"latitude,omitempty"`

	// none (leaf)
	Longitude string `json:"longitude,omitempty"`

	// The Network Element id. (leaf)
	NetworkElementID string `json:"network-element-id,omitempty"`

	// The last time the Network Element was successfully discovered. (leaf)
	NetworkElementLastSuccessfulDiscovery string `json:"network-element-lastSuccessfulDiscovery,omitempty"`

	// The Network Element model. (leaf)
	NetworkElementModel string `json:"network-element-model,omitempty"`

	// The Network Element name. (leaf)
	NetworkElementName string `json:"network-element-name,omitempty"`

	// The Network Element type. (leaf)
	NetworkElementType string `json:"network-element-type,omitempty"`

	// The Network Element vendor. (leaf)
	NetworkElementVendor string `json:"network-element-vendor,omitempty"`

	// The Network Element version. (leaf)
	NetworkElementVersion string `json:"network-element-version,omitempty"`

	// none (leaf)
	Password string `json:"password,omitempty"`

	// none (leaf)
	Port uint16 `json:"port,omitempty"`

	// A label that can be used to define the role of the Network Element. (leaf)
	Role string `json:"role,omitempty"`

	// none (leaf)
	SiteName string `json:"siteName,omitempty"`

	// none (leaf)
	Username string `json:"username,omitempty"`
}

// Validate validates this data tapi network element get network element details post output tapi network element network element
func (m *DataTapiNetworkElementGetNetworkElementDetailsPostOutputTapiNetworkElementNetworkElement) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataTapiNetworkElementGetNetworkElementDetailsPostOutputTapiNetworkElementNetworkElement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataTapiNetworkElementGetNetworkElementDetailsPostOutputTapiNetworkElementNetworkElement) UnmarshalBinary(b []byte) error {
	var res DataTapiNetworkElementGetNetworkElementDetailsPostOutputTapiNetworkElementNetworkElement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
