// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DataTapiNetworkElementGetNetworkElementListPostInput data tapi network element get network element list post input
// swagger:model data_tapi-network-element_get-network-element-list-post-input
type DataTapiNetworkElementGetNetworkElementListPostInput interface{}
