// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OperationsTapiConnectivityDeleteConnectivityServicePostInput operations tapi connectivity delete connectivity service post input
// swagger:model operations_tapi-connectivity_delete-connectivity-service-post-input
type OperationsTapiConnectivityDeleteConnectivityServicePostInput struct {

	// none (leaf)
	TapiConnectivityServiceIDOrName string `json:"tapi-connectivity:service-id-or-name,omitempty"`
}

// Validate validates this operations tapi connectivity delete connectivity service post input
func (m *OperationsTapiConnectivityDeleteConnectivityServicePostInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiConnectivityDeleteConnectivityServicePostInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiConnectivityDeleteConnectivityServicePostInput) UnmarshalBinary(b []byte) error {
	var res OperationsTapiConnectivityDeleteConnectivityServicePostInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
