// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OperationsTapiNetworkElementCreateNetworkElementPostInput operations tapi network element create network element post input
// swagger:model operations_tapi-network-element_create-network-element-post-input
type OperationsTapiNetworkElementCreateNetworkElementPostInput struct {

	// tapi network element netconf connection
	TapiNetworkElementNetconfConnection *OperationsTapiNetworkElementCreateNetworkElementPostInputTapiNetworkElementNetconfConnection `json:"tapi-network-element:netconf-connection,omitempty"`
}

// Validate validates this operations tapi network element create network element post input
func (m *OperationsTapiNetworkElementCreateNetworkElementPostInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTapiNetworkElementNetconfConnection(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OperationsTapiNetworkElementCreateNetworkElementPostInput) validateTapiNetworkElementNetconfConnection(formats strfmt.Registry) error {

	if swag.IsZero(m.TapiNetworkElementNetconfConnection) { // not required
		return nil
	}

	if m.TapiNetworkElementNetconfConnection != nil {
		if err := m.TapiNetworkElementNetconfConnection.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tapi-network-element:netconf-connection")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiNetworkElementCreateNetworkElementPostInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiNetworkElementCreateNetworkElementPostInput) UnmarshalBinary(b []byte) error {
	var res OperationsTapiNetworkElementCreateNetworkElementPostInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiNetworkElementCreateNetworkElementPostInputTapiNetworkElementNetconfConnection none (non-presence)
// swagger:model OperationsTapiNetworkElementCreateNetworkElementPostInputTapiNetworkElementNetconfConnection
type OperationsTapiNetworkElementCreateNetworkElementPostInputTapiNetworkElementNetconfConnection struct {

	// none (leaf)
	IP string `json:"ip,omitempty"`

	// Indication that the Network Element is Discoverable. (leaf)
	IsDiscoverable bool `json:"isDiscoverable,omitempty"`

	// none (leaf)
	Latitude string `json:"latitude,omitempty"`

	// none (leaf)
	Longitude string `json:"longitude,omitempty"`

	// none (leaf)
	Password string `json:"password,omitempty"`

	// none (leaf)
	Port uint16 `json:"port,omitempty"`

	// A label that can be used to define the role of the Network Element. (leaf)
	Role string `json:"role,omitempty"`

	// none (leaf)
	SiteName string `json:"siteName,omitempty"`

	// none (leaf)
	Username string `json:"username,omitempty"`
}

// Validate validates this operations tapi network element create network element post input tapi network element netconf connection
func (m *OperationsTapiNetworkElementCreateNetworkElementPostInputTapiNetworkElementNetconfConnection) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiNetworkElementCreateNetworkElementPostInputTapiNetworkElementNetconfConnection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiNetworkElementCreateNetworkElementPostInputTapiNetworkElementNetconfConnection) UnmarshalBinary(b []byte) error {
	var res OperationsTapiNetworkElementCreateNetworkElementPostInputTapiNetworkElementNetconfConnection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
