// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OperationsTapiNetworkElementDeleteNetworkElementPostInput operations tapi network element delete network element post input
// swagger:model operations_tapi-network-element_delete-network-element-post-input
type OperationsTapiNetworkElementDeleteNetworkElementPostInput struct {

	// none (leaf)
	TapiNetworkElementNetworkElementIDOrName string `json:"tapi-network-element:network-element-id-or-name,omitempty"`
}

// Validate validates this operations tapi network element delete network element post input
func (m *OperationsTapiNetworkElementDeleteNetworkElementPostInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiNetworkElementDeleteNetworkElementPostInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiNetworkElementDeleteNetworkElementPostInput) UnmarshalBinary(b []byte) error {
	var res OperationsTapiNetworkElementDeleteNetworkElementPostInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
