// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// OperationsTapiTopologyGetTopologyListPostInput operations tapi topology get topology list post input
// swagger:model operations_tapi-topology_get-topology-list-post-input
type OperationsTapiTopologyGetTopologyListPostInput interface{}
