// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OperationsTapiTopologyGetLinkDetailsPostOutput operations tapi topology get link details post output
// swagger:model operations_tapi-topology_get-link-details-post-output
type OperationsTapiTopologyGetLinkDetailsPostOutput struct {

	// tapi topology link
	TapiTopologyLink *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink `json:"tapi-topology:link,omitempty"`
}

// Validate validates this operations tapi topology get link details post output
func (m *OperationsTapiTopologyGetLinkDetailsPostOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTapiTopologyLink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutput) validateTapiTopologyLink(formats strfmt.Registry) error {

	if swag.IsZero(m.TapiTopologyLink) { // not required
		return nil
	}

	if m.TapiTopologyLink != nil {
		if err := m.TapiTopologyLink.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tapi-topology:link")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutput) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink none (non-presence)
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink struct {

	// none (leaf)
	// Enum: [LOCKED UNLOCKED]
	AdministrativeState *string `json:"administrative-state,omitempty"`

	// available capacity
	AvailableCapacity *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacity `json:"available-capacity,omitempty"`

	// The list of costs where each cost relates to some aspect of the TopologicalEntity. (list)
	CostCharacteristic []*OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkCostCharacteristicItems0 `json:"cost-characteristic"`

	// Describes the degree to which packets will be delivered out of sequence.
	// Does not apply to TDM as the TDM protocols maintain strict order. (leaf)
	DeliveryOrderCharacteristic string `json:"delivery-order-characteristic,omitempty"`

	// The directionality of the Link.
	// Is applicable to simple Links where all LinkEnds are BIDIRECTIONAL (the Link will be BIDIRECTIONAL) or UNIDIRECTIONAL (the Link will be UNIDIRECTIONAL).
	// Is not present in more complex cases. (leaf)
	// Enum: [BIDIRECTIONAL UNIDIRECTIONAL UNDEFINED_OR_UNKNOWN]
	Direction *string `json:"direction,omitempty"`

	// Describes the degree to which the signal propagated can be errored.
	// Applies to TDM systems as the errored signal will be propagated and not packet as errored packets will be discarded. (leaf)
	ErrorCharacteristic string `json:"error-characteristic,omitempty"`

	// The effect on the latency of a queuing process. This only has significant effect for packet based systems and has a complex characteristic. (list)
	LatencyCharacteristic []*OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLatencyCharacteristicItems0 `json:"latency-characteristic"`

	// layer protocol name
	LayerProtocolName []*string `json:"layer-protocol-name"`

	// none (leaf)
	// Enum: [PLANNED POTENTIAL_AVAILABLE POTENTIAL_BUSY INSTALLED PENDING_REMOVAL]
	LifecycleState *string `json:"lifecycle-state,omitempty"`

	// Describes the acceptable characteristic of lost packets where loss may result from discard due to errors or overflow.
	// Applies to packet systems and not TDM (as for TDM errored signals are propagated unless grossly errored and overflow/underflow turns into timing slips). (leaf)
	LossCharacteristic string `json:"loss-characteristic,omitempty"`

	// List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity. (list)
	Name []*OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNameItems0 `json:"name"`

	// none (list)
	NodeEdgePoint []*OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNodeEdgePointItems0 `json:"node-edge-point"`

	// none (leaf)
	// Enum: [DISABLED ENABLED]
	OperationalState *string `json:"operational-state,omitempty"`

	// none (leaf)
	// Enum: [NO_PROTECTION ONE_PLUS_ONE_PROTECTION ONE_FOR_ONE_PROTECTION ONE_FOR_N_PROTECTION M_FOR_N_PROTECTION ONE_FOR_ONE_BY_N]
	ProtectionType *string `json:"protection-type,omitempty"`

	// Primarily applies to packet systems where a packet may be delivered more than once (in fault recovery for example).
	// It can also apply to TDM where several frames may be received twice due to switching in a system with a large differential propagation delay. (leaf)
	RepeatDeliveryCharacteristic string `json:"repeat-delivery-characteristic,omitempty"`

	// none (leaf)
	// Enum: [PER_DOMAIN_RESTORATION END_TO_END_RESTORATION NA DYNAMIC_RESTORATION PRE_COMPUTED_RESTORATION]
	RestorationPolicy *string `json:"restoration-policy,omitempty"`

	// A list of risk characteristics for consideration in an analysis of shared risk. Each element of the list represents a specific risk consideration. (list)
	RiskCharacteristic []*OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRiskCharacteristicItems0 `json:"risk-characteristic"`

	// Describes the effect of any server integrity enhancement process on the characteristics of the TopologicalEntity. (leaf)
	ServerIntegrityProcessCharacteristic string `json:"server-integrity-process-characteristic,omitempty"`

	// total potential capacity
	TotalPotentialCapacity *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacity `json:"total-potential-capacity,omitempty"`

	// transitioned layer protocol name
	TransitionedLayerProtocolName []string `json:"transitioned-layer-protocol-name"`

	// Describes the duration for which there may be no valid signal propagated. (leaf)
	UnavailableTimeCharacteristic string `json:"unavailable-time-characteristic,omitempty"`

	// UUID: An identifier that is universally unique within an identifier space, where the identifier space is itself globally unique, and immutable. An UUID carries no semantics with respect to the purpose or state of the entity.
	// UUID here uses string representation as defined in RFC 4122.  The canonical representation uses lowercase characters.
	// Pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}
	// Example of a UUID in string representation: f81d4fae-7dec-11d0-a765-00a0c91e6bf6 (leaf)
	UUID string `json:"uuid,omitempty"`

	// Provides details of the specific validation mechanism(s) used to confirm the presence of an intended topologicalEntity. (list)
	ValidationMechanism []*OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkValidationMechanismItems0 `json:"validation-mechanism"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdministrativeState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAvailableCapacity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCostCharacteristic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDirection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLatencyCharacteristic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLayerProtocolName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLifecycleState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNodeEdgePoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOperationalState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtectionType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRestorationPolicy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRiskCharacteristic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalPotentialCapacity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidationMechanism(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeAdministrativeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["LOCKED","UNLOCKED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeAdministrativeStatePropEnum = append(operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeAdministrativeStatePropEnum, v)
	}
}

const (

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAdministrativeStateLOCKED captures enum value "LOCKED"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAdministrativeStateLOCKED string = "LOCKED"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAdministrativeStateUNLOCKED captures enum value "UNLOCKED"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAdministrativeStateUNLOCKED string = "UNLOCKED"
)

// prop value enum
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateAdministrativeStateEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeAdministrativeStatePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateAdministrativeState(formats strfmt.Registry) error {

	if swag.IsZero(m.AdministrativeState) { // not required
		return nil
	}

	// value enum
	if err := m.validateAdministrativeStateEnum("tapi-topology:link"+"."+"administrative-state", "body", *m.AdministrativeState); err != nil {
		return err
	}

	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateAvailableCapacity(formats strfmt.Registry) error {

	if swag.IsZero(m.AvailableCapacity) { // not required
		return nil
	}

	if m.AvailableCapacity != nil {
		if err := m.AvailableCapacity.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tapi-topology:link" + "." + "available-capacity")
			}
			return err
		}
	}

	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateCostCharacteristic(formats strfmt.Registry) error {

	if swag.IsZero(m.CostCharacteristic) { // not required
		return nil
	}

	for i := 0; i < len(m.CostCharacteristic); i++ {
		if swag.IsZero(m.CostCharacteristic[i]) { // not required
			continue
		}

		if m.CostCharacteristic[i] != nil {
			if err := m.CostCharacteristic[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tapi-topology:link" + "." + "cost-characteristic" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeDirectionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["BIDIRECTIONAL","UNIDIRECTIONAL","UNDEFINED_OR_UNKNOWN"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeDirectionPropEnum = append(operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeDirectionPropEnum, v)
	}
}

const (

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkDirectionBIDIRECTIONAL captures enum value "BIDIRECTIONAL"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkDirectionBIDIRECTIONAL string = "BIDIRECTIONAL"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkDirectionUNIDIRECTIONAL captures enum value "UNIDIRECTIONAL"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkDirectionUNIDIRECTIONAL string = "UNIDIRECTIONAL"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkDirectionUNDEFINEDORUNKNOWN captures enum value "UNDEFINED_OR_UNKNOWN"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkDirectionUNDEFINEDORUNKNOWN string = "UNDEFINED_OR_UNKNOWN"
)

// prop value enum
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateDirectionEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeDirectionPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateDirection(formats strfmt.Registry) error {

	if swag.IsZero(m.Direction) { // not required
		return nil
	}

	// value enum
	if err := m.validateDirectionEnum("tapi-topology:link"+"."+"direction", "body", *m.Direction); err != nil {
		return err
	}

	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateLatencyCharacteristic(formats strfmt.Registry) error {

	if swag.IsZero(m.LatencyCharacteristic) { // not required
		return nil
	}

	for i := 0; i < len(m.LatencyCharacteristic); i++ {
		if swag.IsZero(m.LatencyCharacteristic[i]) { // not required
			continue
		}

		if m.LatencyCharacteristic[i] != nil {
			if err := m.LatencyCharacteristic[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tapi-topology:link" + "." + "latency-characteristic" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLayerProtocolNameItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ODU","ETH","DSR","PHOTONIC_MEDIA"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLayerProtocolNameItemsEnum = append(operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLayerProtocolNameItemsEnum, v)
	}
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateLayerProtocolNameItemsEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLayerProtocolNameItemsEnum); err != nil {
		return err
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateLayerProtocolName(formats strfmt.Registry) error {

	if swag.IsZero(m.LayerProtocolName) { // not required
		return nil
	}

	for i := 0; i < len(m.LayerProtocolName); i++ {
		if swag.IsZero(m.LayerProtocolName[i]) { // not required
			continue
		}

		// value enum
		if err := m.validateLayerProtocolNameItemsEnum("tapi-topology:link"+"."+"layer-protocol-name"+"."+strconv.Itoa(i), "body", *m.LayerProtocolName[i]); err != nil {
			return err
		}

	}

	return nil
}

var operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeLifecycleStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PLANNED","POTENTIAL_AVAILABLE","POTENTIAL_BUSY","INSTALLED","PENDING_REMOVAL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeLifecycleStatePropEnum = append(operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeLifecycleStatePropEnum, v)
	}
}

const (

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLifecycleStatePLANNED captures enum value "PLANNED"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLifecycleStatePLANNED string = "PLANNED"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLifecycleStatePOTENTIALAVAILABLE captures enum value "POTENTIAL_AVAILABLE"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLifecycleStatePOTENTIALAVAILABLE string = "POTENTIAL_AVAILABLE"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLifecycleStatePOTENTIALBUSY captures enum value "POTENTIAL_BUSY"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLifecycleStatePOTENTIALBUSY string = "POTENTIAL_BUSY"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLifecycleStateINSTALLED captures enum value "INSTALLED"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLifecycleStateINSTALLED string = "INSTALLED"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLifecycleStatePENDINGREMOVAL captures enum value "PENDING_REMOVAL"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLifecycleStatePENDINGREMOVAL string = "PENDING_REMOVAL"
)

// prop value enum
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateLifecycleStateEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeLifecycleStatePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateLifecycleState(formats strfmt.Registry) error {

	if swag.IsZero(m.LifecycleState) { // not required
		return nil
	}

	// value enum
	if err := m.validateLifecycleStateEnum("tapi-topology:link"+"."+"lifecycle-state", "body", *m.LifecycleState); err != nil {
		return err
	}

	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	for i := 0; i < len(m.Name); i++ {
		if swag.IsZero(m.Name[i]) { // not required
			continue
		}

		if m.Name[i] != nil {
			if err := m.Name[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tapi-topology:link" + "." + "name" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateNodeEdgePoint(formats strfmt.Registry) error {

	if swag.IsZero(m.NodeEdgePoint) { // not required
		return nil
	}

	for i := 0; i < len(m.NodeEdgePoint); i++ {
		if swag.IsZero(m.NodeEdgePoint[i]) { // not required
			continue
		}

		if m.NodeEdgePoint[i] != nil {
			if err := m.NodeEdgePoint[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tapi-topology:link" + "." + "node-edge-point" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeOperationalStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DISABLED","ENABLED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeOperationalStatePropEnum = append(operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeOperationalStatePropEnum, v)
	}
}

const (

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkOperationalStateDISABLED captures enum value "DISABLED"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkOperationalStateDISABLED string = "DISABLED"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkOperationalStateENABLED captures enum value "ENABLED"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkOperationalStateENABLED string = "ENABLED"
)

// prop value enum
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateOperationalStateEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeOperationalStatePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateOperationalState(formats strfmt.Registry) error {

	if swag.IsZero(m.OperationalState) { // not required
		return nil
	}

	// value enum
	if err := m.validateOperationalStateEnum("tapi-topology:link"+"."+"operational-state", "body", *m.OperationalState); err != nil {
		return err
	}

	return nil
}

var operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeProtectionTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["NO_PROTECTION","ONE_PLUS_ONE_PROTECTION","ONE_FOR_ONE_PROTECTION","ONE_FOR_N_PROTECTION","M_FOR_N_PROTECTION","ONE_FOR_ONE_BY_N"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeProtectionTypePropEnum = append(operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeProtectionTypePropEnum, v)
	}
}

const (

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeNOPROTECTION captures enum value "NO_PROTECTION"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeNOPROTECTION string = "NO_PROTECTION"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeONEPLUSONEPROTECTION captures enum value "ONE_PLUS_ONE_PROTECTION"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeONEPLUSONEPROTECTION string = "ONE_PLUS_ONE_PROTECTION"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeONEFORONEPROTECTION captures enum value "ONE_FOR_ONE_PROTECTION"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeONEFORONEPROTECTION string = "ONE_FOR_ONE_PROTECTION"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeONEFORNPROTECTION captures enum value "ONE_FOR_N_PROTECTION"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeONEFORNPROTECTION string = "ONE_FOR_N_PROTECTION"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeMFORNPROTECTION captures enum value "M_FOR_N_PROTECTION"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeMFORNPROTECTION string = "M_FOR_N_PROTECTION"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeONEFORONEBYN captures enum value "ONE_FOR_ONE_BY_N"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkProtectionTypeONEFORONEBYN string = "ONE_FOR_ONE_BY_N"
)

// prop value enum
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateProtectionTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeProtectionTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateProtectionType(formats strfmt.Registry) error {

	if swag.IsZero(m.ProtectionType) { // not required
		return nil
	}

	// value enum
	if err := m.validateProtectionTypeEnum("tapi-topology:link"+"."+"protection-type", "body", *m.ProtectionType); err != nil {
		return err
	}

	return nil
}

var operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeRestorationPolicyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PER_DOMAIN_RESTORATION","END_TO_END_RESTORATION","NA","DYNAMIC_RESTORATION","PRE_COMPUTED_RESTORATION"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeRestorationPolicyPropEnum = append(operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeRestorationPolicyPropEnum, v)
	}
}

const (

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRestorationPolicyPERDOMAINRESTORATION captures enum value "PER_DOMAIN_RESTORATION"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRestorationPolicyPERDOMAINRESTORATION string = "PER_DOMAIN_RESTORATION"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRestorationPolicyENDTOENDRESTORATION captures enum value "END_TO_END_RESTORATION"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRestorationPolicyENDTOENDRESTORATION string = "END_TO_END_RESTORATION"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRestorationPolicyNA captures enum value "NA"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRestorationPolicyNA string = "NA"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRestorationPolicyDYNAMICRESTORATION captures enum value "DYNAMIC_RESTORATION"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRestorationPolicyDYNAMICRESTORATION string = "DYNAMIC_RESTORATION"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRestorationPolicyPRECOMPUTEDRESTORATION captures enum value "PRE_COMPUTED_RESTORATION"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRestorationPolicyPRECOMPUTEDRESTORATION string = "PRE_COMPUTED_RESTORATION"
)

// prop value enum
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateRestorationPolicyEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTypeRestorationPolicyPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateRestorationPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.RestorationPolicy) { // not required
		return nil
	}

	// value enum
	if err := m.validateRestorationPolicyEnum("tapi-topology:link"+"."+"restoration-policy", "body", *m.RestorationPolicy); err != nil {
		return err
	}

	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateRiskCharacteristic(formats strfmt.Registry) error {

	if swag.IsZero(m.RiskCharacteristic) { // not required
		return nil
	}

	for i := 0; i < len(m.RiskCharacteristic); i++ {
		if swag.IsZero(m.RiskCharacteristic[i]) { // not required
			continue
		}

		if m.RiskCharacteristic[i] != nil {
			if err := m.RiskCharacteristic[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tapi-topology:link" + "." + "risk-characteristic" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateTotalPotentialCapacity(formats strfmt.Registry) error {

	if swag.IsZero(m.TotalPotentialCapacity) { // not required
		return nil
	}

	if m.TotalPotentialCapacity != nil {
		if err := m.TotalPotentialCapacity.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tapi-topology:link" + "." + "total-potential-capacity")
			}
			return err
		}
	}

	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) validateValidationMechanism(formats strfmt.Registry) error {

	if swag.IsZero(m.ValidationMechanism) { // not required
		return nil
	}

	for i := 0; i < len(m.ValidationMechanism); i++ {
		if swag.IsZero(m.ValidationMechanism[i]) { // not required
			continue
		}

		if m.ValidationMechanism[i] != nil {
			if err := m.ValidationMechanism[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tapi-topology:link" + "." + "validation-mechanism" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacity Capacity available to be assigned. (non-presence)
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacity
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacity struct {

	// total size
	TotalSize *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSize `json:"total-size,omitempty"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link available capacity
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTotalSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacity) validateTotalSize(formats strfmt.Registry) error {

	if swag.IsZero(m.TotalSize) { // not required
		return nil
	}

	if m.TotalSize != nil {
		if err := m.TotalSize.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tapi-topology:link" + "." + "available-capacity" + "." + "total-size")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacity) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSize Total capacity of the TopologicalEntity in MB/s. In case of bandwidthProfile, this is expected to same as the committedInformationRate. (non-presence)
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSize
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSize struct {

	// none (leaf)
	// Enum: [TB TBPS GB GBPS MB MBPS KB KBPS GHz MHz]
	Unit *string `json:"unit,omitempty"`

	// none (leaf)
	Value uint64 `json:"value,omitempty"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link available capacity total size
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSize) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUnit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeTypeUnitPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["TB","TBPS","GB","GBPS","MB","MBPS","KB","KBPS","GHz","MHz"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeTypeUnitPropEnum = append(operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeTypeUnitPropEnum, v)
	}
}

const (

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitTB captures enum value "TB"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitTB string = "TB"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitTBPS captures enum value "TBPS"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitTBPS string = "TBPS"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitGB captures enum value "GB"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitGB string = "GB"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitGBPS captures enum value "GBPS"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitGBPS string = "GBPS"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitMB captures enum value "MB"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitMB string = "MB"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitMBPS captures enum value "MBPS"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitMBPS string = "MBPS"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitKB captures enum value "KB"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitKB string = "KB"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitKBPS captures enum value "KBPS"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitKBPS string = "KBPS"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitGHz captures enum value "GHz"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitGHz string = "GHz"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitMHz captures enum value "MHz"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeUnitMHz string = "MHz"
)

// prop value enum
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSize) validateUnitEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSizeTypeUnitPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSize) validateUnit(formats strfmt.Registry) error {

	if swag.IsZero(m.Unit) { // not required
		return nil
	}

	// value enum
	if err := m.validateUnitEnum("tapi-topology:link"+"."+"available-capacity"+"."+"total-size"+"."+"unit", "body", *m.Unit); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSize) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSize) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkAvailableCapacityTotalSize
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkCostCharacteristicItems0 operations tapi topology get link details post output tapi topology link cost characteristic items0
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkCostCharacteristicItems0
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkCostCharacteristicItems0 struct {

	// The cost may vary based upon some properties of the TopologicalEntity. The rules for the variation are conveyed by the costAlgorithm. (leaf)
	CostAlgorithm string `json:"cost-algorithm,omitempty"`

	// The cost characteristic will related to some aspect of the TopologicalEntity (e.g. $ cost, routing weight). This aspect will be conveyed by the costName. (leaf)
	CostName string `json:"cost-name,omitempty"`

	// The specific cost. (leaf)
	CostValue string `json:"cost-value,omitempty"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link cost characteristic items0
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkCostCharacteristicItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkCostCharacteristicItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkCostCharacteristicItems0) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkCostCharacteristicItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLatencyCharacteristicItems0 operations tapi topology get link details post output tapi topology link latency characteristic items0
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLatencyCharacteristicItems0
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLatencyCharacteristicItems0 struct {

	// A TopologicalEntity suffers delay caused by the realization of the servers (e.g. distance related; FEC encoding etc.) along with some client specific processing. This is the total average latency effect of the TopologicalEntity (leaf)
	FixedLatencyCharacteristic string `json:"fixed-latency-characteristic,omitempty"`

	// High frequency deviation from true periodicity of a signal and therefore a small high rate of change of transfer latency.
	// Applies to TDM systems (and not packet). (leaf)
	JitterCharacteristic string `json:"jitter-characteristic,omitempty"`

	// The specific queuing latency for the traffic property. (leaf)
	QueingLatencyCharacteristic string `json:"queing-latency-characteristic,omitempty"`

	// The identifier of the specific traffic property to which the queuing latency applies. (leaf)
	TrafficPropertyName string `json:"traffic-property-name,omitempty"`

	// Low frequency deviation from true periodicity of a signal and therefore a small low rate of change of transfer latency.
	// Applies to TDM systems (and not packet). (leaf)
	WanderCharacteristic string `json:"wander-characteristic,omitempty"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link latency characteristic items0
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLatencyCharacteristicItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLatencyCharacteristicItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLatencyCharacteristicItems0) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkLatencyCharacteristicItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNameItems0 operations tapi topology get link details post output tapi topology link name items0
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNameItems0
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNameItems0 struct {

	// The value (leaf)
	Value string `json:"value,omitempty"`

	// The name of the value. The value need not have a name. (leaf)
	ValueName string `json:"value-name,omitempty"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link name items0
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNameItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNameItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNameItems0) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNameItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNodeEdgePointItems0 operations tapi topology get link details post output tapi topology link node edge point items0
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNodeEdgePointItems0
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNodeEdgePointItems0 struct {

	// none (leaf)
	NodeEdgePointUUID string `json:"node-edge-point-uuid,omitempty"`

	// none (leaf)
	NodeUUID string `json:"node-uuid,omitempty"`

	// none (leaf)
	TopologyUUID string `json:"topology-uuid,omitempty"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link node edge point items0
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNodeEdgePointItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNodeEdgePointItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNodeEdgePointItems0) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkNodeEdgePointItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRiskCharacteristicItems0 operations tapi topology get link details post output tapi topology link risk characteristic items0
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRiskCharacteristicItems0
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRiskCharacteristicItems0 struct {

	// The name of the risk characteristic. The characteristic may be related to a specific degree of closeness.
	// For example a particular characteristic may apply to failures that are localized (e.g. to one side of a road) where as another characteristic may relate to failures that have a broader impact (e.g. both sides of a road that crosses a bridge).
	// Depending upon the importance of the traffic being routed different risk characteristics will be evaluated. (leaf)
	RiskCharacteristicName string `json:"risk-characteristic-name,omitempty"`

	// risk identifier list
	RiskIdentifierList []string `json:"risk-identifier-list"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link risk characteristic items0
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRiskCharacteristicItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRiskCharacteristicItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRiskCharacteristicItems0) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkRiskCharacteristicItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacity An optimistic view of the capacity of the TopologicalEntity assuming that any shared capacity is available to be taken. (non-presence)
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacity
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacity struct {

	// total size
	TotalSize *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSize `json:"total-size,omitempty"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link total potential capacity
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTotalSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacity) validateTotalSize(formats strfmt.Registry) error {

	if swag.IsZero(m.TotalSize) { // not required
		return nil
	}

	if m.TotalSize != nil {
		if err := m.TotalSize.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tapi-topology:link" + "." + "total-potential-capacity" + "." + "total-size")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacity) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSize Total capacity of the TopologicalEntity in MB/s. In case of bandwidthProfile, this is expected to same as the committedInformationRate. (non-presence)
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSize
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSize struct {

	// none (leaf)
	// Enum: [TB TBPS GB GBPS MB MBPS KB KBPS GHz MHz]
	Unit *string `json:"unit,omitempty"`

	// none (leaf)
	Value uint64 `json:"value,omitempty"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link total potential capacity total size
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSize) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUnit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeTypeUnitPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["TB","TBPS","GB","GBPS","MB","MBPS","KB","KBPS","GHz","MHz"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeTypeUnitPropEnum = append(operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeTypeUnitPropEnum, v)
	}
}

const (

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitTB captures enum value "TB"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitTB string = "TB"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitTBPS captures enum value "TBPS"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitTBPS string = "TBPS"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitGB captures enum value "GB"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitGB string = "GB"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitGBPS captures enum value "GBPS"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitGBPS string = "GBPS"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitMB captures enum value "MB"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitMB string = "MB"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitMBPS captures enum value "MBPS"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitMBPS string = "MBPS"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitKB captures enum value "KB"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitKB string = "KB"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitKBPS captures enum value "KBPS"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitKBPS string = "KBPS"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitGHz captures enum value "GHz"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitGHz string = "GHz"

	// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitMHz captures enum value "MHz"
	OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeUnitMHz string = "MHz"
)

// prop value enum
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSize) validateUnitEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, operationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSizeTypeUnitPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSize) validateUnit(formats strfmt.Registry) error {

	if swag.IsZero(m.Unit) { // not required
		return nil
	}

	// value enum
	if err := m.validateUnitEnum("tapi-topology:link"+"."+"total-potential-capacity"+"."+"total-size"+"."+"unit", "body", *m.Unit); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSize) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSize) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkTotalPotentialCapacityTotalSize
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkValidationMechanismItems0 operations tapi topology get link details post output tapi topology link validation mechanism items0
// swagger:model OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkValidationMechanismItems0
type OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkValidationMechanismItems0 struct {

	// State of validatiion (leaf)
	LayerProtocolAdjacencyValidated string `json:"layer-protocol-adjacency-validated,omitempty"`

	// Name of mechanism used to validate adjacency (leaf)
	ValidationMechanism string `json:"validation-mechanism,omitempty"`

	// Quality of validation (i.e. how likely is the stated validation to be invalid) (leaf)
	ValidationRobustness string `json:"validation-robustness,omitempty"`
}

// Validate validates this operations tapi topology get link details post output tapi topology link validation mechanism items0
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkValidationMechanismItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkValidationMechanismItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkValidationMechanismItems0) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetLinkDetailsPostOutputTapiTopologyLinkValidationMechanismItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
