// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OperationsTapiTopologyGetTopologyDetailsPostInput operations tapi topology get topology details post input
// swagger:model operations_tapi-topology_get-topology-details-post-input
type OperationsTapiTopologyGetTopologyDetailsPostInput struct {

	// none (leaf)
	TapiTopologyTopologyIDOrName string `json:"tapi-topology:topology-id-or-name,omitempty"`
}

// Validate validates this operations tapi topology get topology details post input
func (m *OperationsTapiTopologyGetTopologyDetailsPostInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationsTapiTopologyGetTopologyDetailsPostInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationsTapiTopologyGetTopologyDetailsPostInput) UnmarshalBinary(b []byte) error {
	var res OperationsTapiTopologyGetTopologyDetailsPostInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
