// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// OperationsTapiNetworkElementDeleteNetworkElementPostOutput operations tapi network element delete network element post output
// swagger:model operations_tapi-network-element_delete-network-element-post-output
type OperationsTapiNetworkElementDeleteNetworkElementPostOutput interface{}
